"""
VORTEX Configuration Module - V17.0 ULTIMATE
Centralized configuration, constants, and prompts
"""

from .settings import (
    Settings,
    AIConfig,
    DatabaseConfig,
    SecurityConfig,
    WebConfig,
    NetworkConfig,
    ScanningConfig,
    QualityConfig,
    LegalConfig,
    MonitoringConfig,
    SystemConfig,
    load_settings,
    load_from_env,
    load_from_file,
    get_settings,
)

from .constants import (
    AUTHORITY_THRESHOLDS,
    EVIDENCE_STANDARDS,
    VULN_SPECIFIC_EVIDENCE,
    AI_LIMITS,
    HEALTH_THRESHOLDS,
    V11_1_TARGETS,
    WORKFLOW_SLA,
    SQLI_ERROR_PATTERNS,
    XSS_REFLECTION_PATTERNS,
    SSRF_INTERNAL_INDICATORS,
    LFI_PATTERNS,
    COMMAND_INJECTION_PATTERNS,
    SECURITY_LIMITS,
    DATA_RETENTION,
    DEFAULT_USER_AGENTS,
    COMMON_HEADERS,
    LOG_LEVELS,
    METRICS_INTERVALS,
    DEFAULT_PATHS,
    AuthorityThresholds,
    EvidenceStandards,
    AIIntegrationLimits,
    OperationalHealthThresholds,
    WorkflowSLATargets,
    SecurityLimits,
)

from .prompts import (
    SYSTEM_PROMPT_CORE,
    VULNERABILITY_ASSESSMENT_PROMPT,
    FALSE_POSITIVE_ANALYSIS_PROMPT,
    BEHAVIORAL_ANALYSIS_PROMPT,
    POC_GENERATION_PROMPT,
    COMPREHENSIVE_ANALYSIS_PROMPT,
    QUALITY_VALIDATION_PROMPT,
    CROSS_VALIDATION_PROMPT,
    HERMES_UNCENSORED_ADDITIONS,
    GEMINI_VALIDATION_ADDITIONS,
    PROMPTS,
    get_prompt,
    get_model_specific_prompt,
)

__all__ = [
    # Settings
    "Settings",
    "AIConfig",
    "DatabaseConfig",
    "SecurityConfig",
    "WebConfig",
    "NetworkConfig",
    "ScanningConfig",
    "QualityConfig",
    "LegalConfig",
    "MonitoringConfig",
    "SystemConfig",
    "load_settings",
    "load_from_env",
    "load_from_file",
    "get_settings",
    
    # Constants
    "AUTHORITY_THRESHOLDS",
    "EVIDENCE_STANDARDS",
    "VULN_SPECIFIC_EVIDENCE",
    "AI_LIMITS",
    "HEALTH_THRESHOLDS",
    "V11_1_TARGETS",
    "WORKFLOW_SLA",
    "SQLI_ERROR_PATTERNS",
    "XSS_REFLECTION_PATTERNS",
    "SSRF_INTERNAL_INDICATORS",
    "LFI_PATTERNS",
    "COMMAND_INJECTION_PATTERNS",
    "SECURITY_LIMITS",
    "DATA_RETENTION",
    "DEFAULT_USER_AGENTS",
    "COMMON_HEADERS",
    "LOG_LEVELS",
    "METRICS_INTERVALS",
    "DEFAULT_PATHS",
    "AuthorityThresholds",
    "EvidenceStandards",
    "AIIntegrationLimits",
    "OperationalHealthThresholds",
    "WorkflowSLATargets",
    "SecurityLimits",
    
    # Prompts
    "SYSTEM_PROMPT_CORE",
    "VULNERABILITY_ASSESSMENT_PROMPT",
    "FALSE_POSITIVE_ANALYSIS_PROMPT",
    "BEHAVIORAL_ANALYSIS_PROMPT",
    "POC_GENERATION_PROMPT",
    "COMPREHENSIVE_ANALYSIS_PROMPT",
    "QUALITY_VALIDATION_PROMPT",
    "CROSS_VALIDATION_PROMPT",
    "HERMES_UNCENSORED_ADDITIONS",
    "GEMINI_VALIDATION_ADDITIONS",
    "PROMPTS",
    "get_prompt",
    "get_model_specific_prompt",
]