"""
VORTEX Formatting Utilities - V17.0 ULTIMATE
Report formatting for findings, submissions, and evidence
"""

import logging
from typing import Dict, Any, Optional
from datetime import datetime

logger = logging.getLogger(__name__)


def format_finding_report(finding: Dict[str, Any]) -> str:
    """
    Format finding as detailed report.
    
    Args:
        finding: Finding data dictionary
        
    Returns:
        Formatted report string
    """
    try:
        report = f"""
VORTEX Security Finding Report
{'='*60}

Finding ID: {finding.get('id', 'N/A')}
Status: {finding.get('status', 'N/A')}
Severity: {finding.get('severity', 'N/A')}
Type: {finding.get('type', 'N/A')}

Target Information:
  URL: {finding.get('url', 'N/A')}
  Parameter: {finding.get('parameter', 'N/A')}
  Method: {finding.get('method', 'GET')}

Evidence:
{finding.get('evidence', 'No evidence available')}

Confidence Scores:
  Heuristic: {finding.get('heuristic_score', 0.0):.2f}
  System Verification: {finding.get('system_confidence', 0.0):.2f}
  AI Confidence: {finding.get('ai_confidence', 0.0):.2f}

Timestamp: {finding.get('created_at', datetime.utcnow().isoformat())}
{'='*60}
"""
        return report.strip()
    except Exception as e:
        logger.error(f"Report formatting error: {e}")
        return "Error formatting report"


def format_submission(finding: Dict[str, Any]) -> str:
    """
    Format finding for bug bounty submission.
    
    Args:
        finding: Finding data dictionary
        
    Returns:
        Formatted submission string
    """
    try:
        submission = f"""
# {finding.get('type', 'Security Vulnerability')} - {finding.get('severity', 'Unknown')} Severity

## Summary
A {finding.get('severity', 'unknown').lower()} severity {finding.get('type', 'vulnerability')} was discovered in the target application.

## Vulnerability Details
- **URL**: {finding.get('url', 'N/A')}
- **Parameter**: {finding.get('parameter', 'N/A')}
- **Method**: {finding.get('method', 'GET')}
- **Type**: {finding.get('type', 'N/A')}

## Proof of Concept
```
{finding.get('poc', 'See evidence section')}
```

## Evidence
{finding.get('evidence', 'No detailed evidence provided')}

## Impact
{finding.get('impact_description', 'This vulnerability could allow attackers to compromise the application security.')}

## Remediation
{finding.get('remediation', 'Apply appropriate security controls and input validation.')}

---
*Report generated by VORTEX v17.0 Security Scanner*
*Timestamp: {datetime.utcnow().isoformat()}*
"""
        return submission.strip()
    except Exception as e:
        logger.error(f"Submission formatting error: {e}")
        return "Error formatting submission"


def format_evidence(evidence_data: Dict[str, Any]) -> str:
    """
    Format evidence for display.
    
    Args:
        evidence_data: Evidence data dictionary
        
    Returns:
        Formatted evidence string
    """
    try:
        return f"""
Evidence Summary:
  Type: {evidence_data.get('type', 'N/A')}
  Determinism: {evidence_data.get('determinism_score', 0.0):.2f}
  
Request:
  {evidence_data.get('request', 'N/A')}
  
Response:
  Status: {evidence_data.get('response_status', 'N/A')}
  Size: {evidence_data.get('response_size', 0)} bytes
  Time: {evidence_data.get('response_time', 0.0):.3f}s
  
Matched Pattern:
  {evidence_data.get('matched_pattern', 'N/A')}
"""
    except Exception as e:
        logger.error(f"Evidence formatting error: {e}")
        return "Error formatting evidence"


def generate_markdown_report(findings: list) -> str:
    """
    Generate Markdown report for multiple findings.
    
    Args:
        findings: List of finding dictionaries
        
    Returns:
        Markdown formatted report
    """
    try:
        report = f"""# VORTEX Security Scan Report

**Generated**: {datetime.utcnow().isoformat()}
**Total Findings**: {len(findings)}

## Summary

| Status | Count |
|--------|-------|
"""
        # Add summary statistics
        status_counts = {}
        for finding in findings:
            status = finding.get('status', 'UNKNOWN')
            status_counts[status] = status_counts.get(status, 0) + 1
        
        for status, count in status_counts.items():
            report += f"| {status} | {count} |\n"
        
        report += "\n## Detailed Findings\n\n"
        
        for i, finding in enumerate(findings, 1):
            report += f"""### {i}. {finding.get('type', 'Unknown')} - {finding.get('severity', 'Unknown')}

**URL**: {finding.get('url', 'N/A')}
**Status**: {finding.get('status', 'N/A')}
**Confidence**: {finding.get('confidence', 0.0):.2f}

**Evidence**:
```
{finding.get('evidence', 'No evidence')[:200]}...
```

---

"""
        
        return report
    except Exception as e:
        logger.error(f"Markdown report generation error: {e}")
        return "# Error Generating Report"


def generate_html_report(findings: list) -> str:
    """
    Generate HTML report for multiple findings.
    
    Args:
        findings: List of finding dictionaries
        
    Returns:
        HTML formatted report
    """
    try:
        html = f"""<!DOCTYPE html>
<html>
<head>
    <title>VORTEX Security Report</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 20px; }}
        .header {{ background: #333; color: white; padding: 20px; }}
        .finding {{ border: 1px solid #ddd; margin: 10px 0; padding: 15px; }}
        .critical {{ border-left: 4px solid #dc3545; }}
        .high {{ border-left: 4px solid #ffc107; }}
        .medium {{ border-left: 4px solid #17a2b8; }}
        .low {{ border-left: 4px solid #28a745; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>VORTEX Security Scan Report</h1>
        <p>Generated: {datetime.utcnow().isoformat()}</p>
        <p>Total Findings: {len(findings)}</p>
    </div>
    
    <h2>Findings</h2>
"""
        
        for finding in findings:
            severity = finding.get('severity', 'UNKNOWN').lower()
            html += f"""
    <div class="finding {severity}">
        <h3>{finding.get('type', 'Unknown')} - {finding.get('severity', 'Unknown')}</h3>
        <p><strong>URL:</strong> {finding.get('url', 'N/A')}</p>
        <p><strong>Status:</strong> {finding.get('status', 'N/A')}</p>
        <p><strong>Confidence:</strong> {finding.get('confidence', 0.0):.2f}</p>
        <pre>{finding.get('evidence', 'No evidence')[:200]}...</pre>
    </div>
"""
        
        html += """
</body>
</html>
"""
        return html
    except Exception as e:
        logger.error(f"HTML report generation error: {e}")
        return "<html><body><h1>Error Generating Report</h1></body></html>"


__all__ = [
    'format_finding_report',
    'format_submission',
    'format_evidence',
    'generate_markdown_report',
    'generate_html_report',
]