"""
VORTEX Legal Compliance Utilities - V17.0 ULTIMATE
Legal compliance helper functions and validators

Per .clinerules LEGAL_COMPLIANCE:
- Bug bounty context validation
- Ethical boundaries enforcement
- PII detection helpers
- Legal documentation support

FEATURES:
- Legal context validation
- Compliance checking utilities
- PII pattern detection helpers
- Documentation formatting
"""

import re
import logging
from typing import List, Dict, Optional, Any, Set
from dataclasses import dataclass
from datetime import datetime

logger = logging.getLogger(__name__)


@dataclass
class LegalContext:
    """Legal context for security testing."""
    program_name: str
    authorization_type: str  # 'bug_bounty', 'pentest', 'internal'
    scope_verified: bool
    consent_documented: bool
    restrictions: List[str]
    created_at: datetime
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            'program_name': self.program_name,
            'authorization_type': self.authorization_type,
            'scope_verified': self.scope_verified,
            'consent_documented': self.consent_documented,
            'restrictions': self.restrictions,
            'created_at': self.created_at.isoformat()
        }


class LegalValidator:
    """
    Legal compliance validation utilities.
    
    Ensures testing activities comply with legal requirements.
    """
    
    # Valid authorization types
    VALID_AUTHORIZATION_TYPES = {
        'bug_bounty',      # Bug bounty program
        'pentest',         # Authorized penetration test
        'internal',        # Internal security testing
        'research'         # Security research with consent
    }
    
    @staticmethod
    def validate_authorization_type(auth_type: str) -> bool:
        """
        Validate authorization type.
        
        Args:
            auth_type: Authorization type
            
        Returns:
            True if valid
        """
        return auth_type in LegalValidator.VALID_AUTHORIZATION_TYPES
    
    @staticmethod
    def validate_legal_context(context: LegalContext) -> tuple[bool, List[str]]:
        """
        Validate legal context.
        
        Args:
            context: Legal context to validate
            
        Returns:
            (is_valid, error_messages)
        """
        errors = []
        
        # Check authorization type
        if not LegalValidator.validate_authorization_type(context.authorization_type):
            errors.append(f"Invalid authorization type: {context.authorization_type}")
        
        # Check scope verification
        if not context.scope_verified:
            errors.append("Scope not verified - testing not authorized")
        
        # Check consent documentation
        if not context.consent_documented:
            errors.append("Consent not documented - legal requirement not met")
        
        # Bug bounty specific checks
        if context.authorization_type == 'bug_bounty':
            if not context.program_name:
                errors.append("Bug bounty program name required")
        
        is_valid = len(errors) == 0
        
        return is_valid, errors
    
    @staticmethod
    def create_legal_disclaimer() -> str:
        """
        Create legal disclaimer for reports.
        
        Returns:
            Disclaimer text
        """
        return """
LEGAL DISCLAIMER

This security assessment was conducted within the scope of an authorized bug bounty 
program or security testing engagement. All testing activities were performed with 
explicit authorization and in compliance with applicable laws and regulations.

The findings reported herein are provided for security improvement purposes only and 
should be addressed according to the organization's security policies and procedures.

Unauthorized reproduction, distribution, or use of this report is strictly prohibited.

Generated by VORTEX Security Assessment Platform
""".strip()
    
    @staticmethod
    def format_authorization_statement(context: LegalContext) -> str:
        """
        Format authorization statement for documentation.
        
        Args:
            context: Legal context
            
        Returns:
            Authorization statement
        """
        return f"""
AUTHORIZATION STATEMENT

Program: {context.program_name}
Authorization Type: {context.authorization_type.upper()}
Scope Verified: {'Yes' if context.scope_verified else 'No'}
Consent Documented: {'Yes' if context.consent_documented else 'No'}
Assessment Date: {context.created_at.strftime('%Y-%m-%d %H:%M:%S UTC')}

This assessment was conducted in accordance with the program's scope and rules.
All testing activities were performed ethically and responsibly.
""".strip()


class PIIPatternHelper:
    """
    Helper for PII pattern detection.
    
    Provides regex patterns and validators for common PII types.
    """
    
    # Common PII patterns (from legal_compliance.py)
    PATTERNS = {
        'email': r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b',
        'phone_us': r'\b(?:\+?1[-.]?)?\(?([0-9]{3})\)?[-.]?([0-9]{3})[-.]?([0-9]{4})\b',
        'phone_international': r'\+[0-9]{1,3}[-.\s]?(?:\([0-9]{1,4}\)|[0-9]{1,4})[-.\s]?[0-9]{1,4}[-.\s]?[0-9]{1,9}',
        'ssn': r'\b(?!000|666|9\d{2})\d{3}-(?!00)\d{2}-(?!0000)\d{4}\b',
        'credit_card': r'\b(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|6(?:011|5[0-9]{2})[0-9]{12}|(?:2131|1800|35\d{3})\d{11})\b',
        'ip_address': r'\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b',
        'url': r'https?://(?:www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b(?:[-a-zA-Z0-9()@:%_\+.~#?&/=]*)',
    }
    
    @staticmethod
    def detect_pii_patterns(text: str) -> Dict[str, List[str]]:
        """
        Detect PII patterns in text.
        
        Args:
            text: Text to scan
            
        Returns:
            Dictionary of detected PII by type
        """
        detected = {}
        
        for pii_type, pattern in PIIPatternHelper.PATTERNS.items():
            matches = re.findall(pattern, text)
            if matches:
                detected[pii_type] = matches
        
        return detected
    
    @staticmethod
    def has_pii(text: str) -> bool:
        """
        Check if text contains any PII.
        
        Args:
            text: Text to check
            
        Returns:
            True if PII detected
        """
        detected = PIIPatternHelper.detect_pii_patterns(text)
        return len(detected) > 0
    
    @staticmethod
    def redact_pii_simple(text: str, replacement: str = "[REDACTED]") -> str:
        """
        Simple PII redaction.
        
        Args:
            text: Text to redact
            replacement: Replacement string
            
        Returns:
            Redacted text
        """
        redacted = text
        
        for pii_type, pattern in PIIPatternHelper.PATTERNS.items():
            redacted = re.sub(pattern, replacement, redacted)
        
        return redacted


class EthicalBoundariesChecker:
    """
    Ethical boundaries validation.
    
    Ensures testing respects ethical boundaries per .clinerules.
    """
    
    # Prohibited actions (always unethical)
    PROHIBITED_ACTIONS = {
        'data_destruction',
        'service_disruption',
        'unauthorized_access',
        'privacy_violation',
        'social_engineering_unauthorized',
        'physical_access',
        'minor_targeting'
    }
    
    # Restricted actions (require specific authorization)
    RESTRICTED_ACTIONS = {
        'credential_testing',
        'rate_limiting_bypass',
        'large_scale_scanning',
        'automated_exploitation'
    }
    
    @staticmethod
    def validate_action(action: str, has_specific_authorization: bool = False) -> tuple[bool, Optional[str]]:
        """
        Validate if action is ethically permissible.
        
        Args:
            action: Action to validate
            has_specific_authorization: Whether specific authorization exists
            
        Returns:
            (is_permitted, reason)
        """
        # Check prohibited
        if action in EthicalBoundariesChecker.PROHIBITED_ACTIONS:
            return False, f"Action '{action}' is prohibited - violates ethical boundaries"
        
        # Check restricted
        if action in EthicalBoundariesChecker.RESTRICTED_ACTIONS:
            if not has_specific_authorization:
                return False, f"Action '{action}' requires specific authorization"
        
        return True, None
    
    @staticmethod
    def get_ethical_guidelines() -> List[str]:
        """
        Get ethical testing guidelines.
        
        Returns:
            List of guidelines
        """
        return [
            "Test only within authorized scope",
            "Avoid actions that could harm systems or users",
            "Respect user privacy and data protection",
            "Stop testing immediately if risks are identified",
            "Report findings responsibly through proper channels",
            "Do not access or modify data beyond what's necessary",
            "Avoid social engineering without explicit authorization",
            "Never target minors or vulnerable populations",
            "Maintain confidentiality of discovered vulnerabilities",
            "Follow responsible disclosure practices"
        ]


class ComplianceReporter:
    """
    Compliance reporting utilities.
    
    Formats findings for legal compliance requirements.
    """
    
    @staticmethod
    def create_compliance_header(context: LegalContext) -> str:
        """
        Create compliance header for reports.
        
        Args:
            context: Legal context
            
        Returns:
            Formatted header
        """
        header = f"""
{'='*80}
SECURITY ASSESSMENT REPORT
{'='*80}

{LegalValidator.format_authorization_statement(context)}

{LegalValidator.create_legal_disclaimer()}

{'='*80}
""".strip()
        
        return header
    
    @staticmethod
    def format_finding_for_submission(finding_data: Dict[str, Any],
                                     context: LegalContext) -> str:
        """
        Format finding for bug bounty submission.
        
        Args:
            finding_data: Finding data
            context: Legal context
            
        Returns:
            Formatted submission text
        """
        submission = f"""
SECURITY FINDING SUBMISSION

Program: {context.program_name}
Finding ID: {finding_data.get('id', 'N/A')}
Severity: {finding_data.get('severity', 'UNKNOWN').upper()}
Type: {finding_data.get('finding_type', 'UNKNOWN')}

SUMMARY
{finding_data.get('title', 'Security Vulnerability Identified')}

DESCRIPTION
{finding_data.get('description', 'See technical details below.')}

IMPACT
{finding_data.get('impact', 'Potential security impact identified.')}

REPRODUCTION STEPS
{finding_data.get('reproduction_steps', '1. Navigate to vulnerable endpoint\n2. Execute proof of concept')}

TECHNICAL DETAILS
URL: {finding_data.get('url', 'N/A')}
Parameter: {finding_data.get('parameter', 'N/A')}
Method: {finding_data.get('method', 'N/A')}

EVIDENCE
{finding_data.get('evidence', 'Evidence attached separately.')}

REMEDIATION
{finding_data.get('remediation', 'Recommended security patch or configuration change.')}

---
This finding was discovered through authorized security testing.
All testing was conducted ethically and within program scope.
""".strip()
        
        return submission
    
    @staticmethod
    def create_audit_record(finding_id: str,
                          action: str,
                          actor: str = "system",
                          metadata: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """
        Create audit record for compliance.
        
        Args:
            finding_id: Finding identifier
            action: Action performed
            actor: Who performed the action
            metadata: Additional metadata
            
        Returns:
            Audit record
        """
        return {
            'finding_id': finding_id,
            'action': action,
            'actor': actor,
            'timestamp': datetime.utcnow().isoformat(),
            'metadata': metadata or {},
            'compliance_version': 'VORTEX_V17.0'
        }


class ScopeValidator:
    """
    Scope validation utilities.
    
    Validates targets are within authorized scope.
    """
    
    @staticmethod
    def is_private_ip(ip: str) -> bool:
        """
        Check if IP is private/internal.
        
        Args:
            ip: IP address
            
        Returns:
            True if private
        """
        private_ranges = [
            r'^10\.',
            r'^172\.(1[6-9]|2[0-9]|3[0-1])\.',
            r'^192\.168\.',
            r'^127\.',
            r'^169\.254\.',
            r'^::1$',
            r'^fe80:',
            r'^fc00:',
            r'^fd00:'
        ]
        
        return any(re.match(pattern, ip) for pattern in private_ranges)
    
    @staticmethod
    def extract_domain(url: str) -> Optional[str]:
        """
        Extract domain from URL.
        
        Args:
            url: URL string
            
        Returns:
            Domain or None
        """
        from urllib.parse import urlparse
        
        try:
            parsed = urlparse(url)
            return parsed.netloc
        except Exception:
            return None
    
    @staticmethod
    def is_in_scope(url: str, allowed_domains: Set[str]) -> bool:
        """
        Check if URL is in authorized scope.
        
        Args:
            url: URL to check
            allowed_domains: Set of allowed domains
            
        Returns:
            True if in scope
        """
        domain = ScopeValidator.extract_domain(url)
        
        if not domain:
            return False
        
        # Exact match
        if domain in allowed_domains:
            return True
        
        # Subdomain match
        for allowed_domain in allowed_domains:
            if domain.endswith(f".{allowed_domain}"):
                return True
        
        return False


# Global instances
global_legal_validator = LegalValidator()
global_pii_helper = PIIPatternHelper()
global_ethical_checker = EthicalBoundariesChecker()
global_compliance_reporter = ComplianceReporter()
global_scope_validator = ScopeValidator()