"""
VORTEX Domain Layer - V17.0 ULTIMATE
Core domain models, enums, and business logic
"""

from .enums import (
    VerificationStatus,
    FindingType,
    FindingSeverity,
    AIVerdict,
    ImpactLevel,
    ConfidenceSource,
    EvidenceLevel,
    MatchType,
    AIAvailabilityStatus,
    AuthorityLevel,
    ScanMode,
    QueuePriority,
    HealthStatus,
    ManualReviewPriority,
    LogLevel,
    ComplianceStatus,
    ReportFormat,
)

from .models import (
    VerificationResult,
    AIAnalysisResult,
    BehaviorAssessment,
    FastPathAssessment,
    EvidenceQuality,
    AssessmentResult,
    ManualReviewSLA,
    SystemHealthMetrics,
    HealthAssessment,
    TuningRecommendation,
    SystemHealthReport,
    HealthAlert,
    WorkflowMetrics,
    ScanConfiguration,
    ScanResult,
)

from .events import (
    DomainEvent,
    FindingDetectedEvent,
    StateTransitionEvent,
    AIAnalysisCompleteEvent,
    SystemVerificationCompleteEvent,
    AuthorityViolationEvent,
    FastPathPromotionEvent,
    ManualReviewRegisteredEvent,
    ManualReviewOverdueEvent,
    HealthThresholdViolationEvent,
    AutoTuningExecutedEvent,
    ComplianceViolationEvent,
    EvidenceIntegrityEvent,
    WorkflowErrorEvent,
    EventBus,
    event_bus,
)

from .evidence import (
    EvidencePackage,
    DeterministicEvidenceCriteria,
    BehavioralEvidenceAnalysis,
    EvidenceQualityScore,
    VULNERABILITY_EVIDENCE_CRITERIA,
    get_evidence_criteria,
)

from .compliance import (
    ComplianceViolationType,
    PIIType,
    PIIPattern,
    PIIDetectionResult,
    ScopeValidationResult,
    ComplianceCheck,
    ComplianceReport,
    LegalContact,
    ResponsibleDisclosurePolicy,
    DataRetentionPolicy,
    EthicalBoundary,
    ETHICAL_BOUNDARIES,
    PII_PATTERNS,
    validate_ethical_boundaries,
)

from .lifecycle import (
    VALID_STATE_TRANSITIONS,
    is_valid_transition,
    get_valid_transitions,
    is_terminal_state,
    StateTransition,
    FindingLifecycle,
    ManualReviewQueue,
    calculate_manual_review_priority,
    calculate_sla_hours,
)

__all__ = [
    # Enums
    "VerificationStatus",
    "FindingType",
    "FindingSeverity",
    "AIVerdict",
    "ImpactLevel",
    "ConfidenceSource",
    "EvidenceLevel",
    "MatchType",
    "AIAvailabilityStatus",
    "AuthorityLevel",
    "ScanMode",
    "QueuePriority",
    "HealthStatus",
    "ManualReviewPriority",
    "LogLevel",
    "ComplianceStatus",
    "ReportFormat",
    
    # Models
    "VerificationResult",
    "AIAnalysisResult",
    "BehaviorAssessment",
    "FastPathAssessment",
    "EvidenceQuality",
    "AssessmentResult",
    "ManualReviewSLA",
    "SystemHealthMetrics",
    "HealthAssessment",
    "TuningRecommendation",
    "SystemHealthReport",
    "HealthAlert",
    "WorkflowMetrics",
    "ScanConfiguration",
    "ScanResult",
    
    # Events
    "DomainEvent",
    "FindingDetectedEvent",
    "StateTransitionEvent",
    "AIAnalysisCompleteEvent",
    "SystemVerificationCompleteEvent",
    "AuthorityViolationEvent",
    "FastPathPromotionEvent",
    "ManualReviewRegisteredEvent",
    "ManualReviewOverdueEvent",
    "HealthThresholdViolationEvent",
    "AutoTuningExecutedEvent",
    "ComplianceViolationEvent",
    "EvidenceIntegrityEvent",
    "WorkflowErrorEvent",
    "EventBus",
    "event_bus",
    
    # Evidence
    "EvidencePackage",
    "DeterministicEvidenceCriteria",
    "BehavioralEvidenceAnalysis",
    "EvidenceQualityScore",
    "VULNERABILITY_EVIDENCE_CRITERIA",
    "get_evidence_criteria",
    
    # Compliance
    "ComplianceViolationType",
    "PIIType",
    "PIIPattern",
    "PIIDetectionResult",
    "ScopeValidationResult",
    "ComplianceCheck",
    "ComplianceReport",
    "LegalContact",
    "ResponsibleDisclosurePolicy",
    "DataRetentionPolicy",
    "EthicalBoundary",
    "ETHICAL_BOUNDARIES",
    "PII_PATTERNS",
    "validate_ethical_boundaries",
    
    # Lifecycle
    "VALID_STATE_TRANSITIONS",
    "is_valid_transition",
    "get_valid_transitions",
    "is_terminal_state",
    "StateTransition",
    "FindingLifecycle",
    "ManualReviewQueue",
    "calculate_manual_review_priority",
    "calculate_sla_hours",
]